# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '0004_auto_20160423_0400'),
        ('mosaicrenderer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweeterBlocklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TweetMosaicSource',
            fields=[
                ('mosaicsourceimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mosaicrenderer.MosaicSourceImage')),
                ('tweet_id', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('message', models.TextField(default='', help_text='maybe not always the full message/post')),
                ('username', models.CharField(max_length=128)),
                ('image_url', models.URLField(blank=True, help_text='url to IMAGE')),
                ('geo', models.CharField(max_length=128)),
            ],
            bases=('mosaicrenderer.mosaicsourceimage',),
        ),
        migrations.CreateModel(
            name='TwitterMosaic',
            fields=[
                ('mosaic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mosaicrenderer.Mosaic')),
                ('twitter_search', models.TextField(blank=True)),
                ('collector', models.ForeignKey(blank=True, help_text='Which account will collect the tweets, under a quota. Using the same account for more than one active mosaic split your tweet quota between the two queries (i.e. you will get half as many tweets/hour or less)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='default.UserSocialAuth')),
            ],
            bases=('mosaicrenderer.mosaic',),
        ),
    ]
