# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'paused'), (5, 'completed')])),
                ('image_width', models.PositiveIntegerField(null=True)),
                ('image_height', models.PositiveIntegerField(null=True)),
                ('target_image', models.ImageField(blank=True, height_field='image_width', upload_to='', width_field='image_height')),
                ('title', models.TextField(blank=True)),
                ('minimum_image_count', models.PositiveIntegerField()),
                ('incremental_update_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_render', models.DateTimeField(blank=True, null=True)),
                ('public_url', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MosaicRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_image', models.ImageField(blank=True, upload_to='')),
                ('mosaic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicrenderer.Mosaic')),
            ],
        ),
        migrations.CreateModel(
            name='MosaicSourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='mosaicrender',
            name='source_images',
            field=models.ManyToManyField(related_name='renders', to='mosaicrenderer.MosaicSourceImage'),
        ),
        migrations.AddField(
            model_name='mosaic',
            name='source_images',
            field=models.ManyToManyField(related_name='mosaics', to='mosaicrenderer.MosaicSourceImage'),
        ),
    ]
